### PR TITLE
Time and Title now have more space in between

### PR DESCRIPTION
**Pull request by vgezer**
@georgehrke A new commit only including that.

### CODE REVIEW

**Comment by georgehrke** [comment]
cc @owncloud/designers

**Comment by jbtbnl** [comment]
@wakeup please include a useful description because now I need to search for what has been fixed exactly.

**Comment by jbtbnl** [comment]
Nonetheless :+1:

**Comment by georgehrke** [comment]
@wakeup Would you mind contributing this fix to [upstream](https://github.com/arshaw/fullcalendar) as well?

**Comment by vgezer** [comment]
Here is the before/after images:

web arayz1

web arayz1

When I first made a PR, it was more clear, but it seems this has already been solved so we can close this without merging.

@georgehrke Also we probably won't need to report into upstream. What do you think?

**Comment by georgehrke** [comment]
> @georgehrke Also we probably won't need to report into upstream. What do you think?

If it was solved in the meantime and this needs no merge: yes

**Comment by jbtbnl** [comment]
@wakeup what do you mean by that? In calendar/master the issue still exists. If it has been fixed in the latest FullCalendar version then we should merge that.

**Comment by jbtbnl** [comment]
Also, for the second screenshot the second line of appointment "Calligra" should be indented as well.

**Comment by jancborchardt** [comment]
This is something we should fix upstream only, not manually in ownCloud.

**Comment by georgehrke** [comment]
see jan's comment

**Pull request closed without merging**
