### PR TITLE
Restore share dropdown functionality

### PR DESCRIPTION
**Pull request by PVince81**
Imports the old share.js code required for the share dropdown
- [x] TODO: fix layout to look like it did with 8.1
- [x] TODO: fix checkboxes (@Henni can you help with this ?)

@blizzz @DeepDiver1975 @rullzer FYI

### CODE REVIEW

**Comment by PVince81** [comment]
Hmmm, I compared with the 8.1 version and the layout was already broken there.

**Comment by Henni** [comment]
@PVince81 checkboxes should be fixed. Please take a look.

**Comment by PVince81** [comment]
Thanks @Henni 

@georgehrke can we merge this ?

**Comment by rullzer** [comment]
Seems to be working.
:+1:

**Comment by PVince81** [comment]
@rullzer thanks

**Pull request merged**
