### PR TITLE
Make 'Enter' key trigger 'click' for adding new calendar or edit its name.

### PR DESCRIPTION
**Pull request by wtayyeb**
@wakeup asked me [in #389 comments](https://github.com/owncloud/calendar/pull/389#issuecomment-40265945) to create another branch and make seperate Pull Request for this.

### CODE REVIEW

**Comment by vgezer** [comment]
@wtayyeb Thanks. :+1: Tested and works.

**Comment by vgezer** [comment]
cc: @georgehrke

**Comment by jancborchardt** [comment]
@jbtbnl this probably is best for you to test?

**Comment by georgehrke** [comment]
ping @jbtbnl

**Comment by jbtbnl** [comment]
:+1: we need this in Contacts as well
cc @tanghus

**Comment by tanghus** [comment]
This already works in contacts app.

**Comment by jancborchardt** [comment]
Btw @wtayyeb you are very welcome in our IRC channel #owncloud-calendar! :)

**Pull request merged**
