### PR TITLE
in oc8 or later share_backend need to implement isShareTypeAllowed()

### PR DESCRIPTION
**Pull request by schiessle**
share_backend was extended with isShareTypeAllowed here: https://github.com/owncloud/core/pull/12749

Will be needed after the PR on core was merged

### CODE REVIEW

**Comment by schiessle** [comment]
The changes are now I core, @georgehrke please have a look and merge it if you think it is OK.

**Comment by jancborchardt** [comment]
Fixes the completely-non-loading for me, but still issues remain:

```
Uncaught TypeError: undefined is not a function (fullcalendar.js, line 357)
Uncaught TypeError: Cannot read property 'left' of undefined (calendar.js, line 120)
```

@georgehrke

**Comment by schiessle** [comment]
seems to be unrelated to my changes. @georgehrke what do you think?

**Comment by georgehrke** [comment]
@schiesbn Does this fix https://github.com/owncloud/calendar/issues/619#issuecomment-66261173? if not please answer my question there.

**Comment by georgehrke** [comment]
@jancborchardt Your issue seems related to https://github.com/owncloud/calendar/issues/530

**Pull request merged**
