### PR TITLE
Fixed weird event registration

### LINKED ISSUE #463: Events cannot be marked as private
### Steps to reproduce
1. Create event
2. Open details
3. No possibility to mark event as private
### Expected behaviour

Before 9.0 an event could be marked as private, so these marked events would not be seen if the calendar is shared
### Actual behaviour

No field for privacy
### Server configuration

**ownCloud version:9.0.1

**Calendar version:1.1

### PR DESCRIPTION
**Pull request by PVince81**
This fixes click handlers on the document

Fixes https://github.com/owncloud/calendar/issues/463

Please review @MorrisJobke @jancborchardt @wakeup

### CODE REVIEW

**Comment by PVince81** [comment]
@maethor please help testing this

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@PVince81 Just tested the code locally with your tip from #463 ;)

**Comment by MorrisJobke** [comment]
But this doesn't fix the share dropdown issue. This just fixes the undefined error logs.

**Comment by PVince81** [comment]
Really ? After that fix the share dropdown closes itself when I click outside (or at least I clicked in the panel)

**Comment by MorrisJobke** [comment]
@PVince81 I though the issue was about clicking the share icon again

**Comment by PVince81** [comment]
Oops, yes. Then I misread because I was observing that other issue.
After merging this, let's reopen that ticket to investigate the "click on the link" case.

**Comment by JohnDoe42** [comment]
This fix works for me. Thanks!

**Comment by PVince81** [comment]
@JohnDoe42 thanks.

Xiflite on IRC also reported that this patch works. Merging.

**Comment by PVince81** [comment]
Backported to stable7 as 4390e1251b5cdd4c3695276da7227ae9b74ac1c3

**Pull request merged**
