### PR TITLE
Add miniColors lib

### PR DESCRIPTION
**Pull request by jbtbnl**
as this is now removed in core, it should be shipped with calendar. Otherwise the ownCloud instance is broken if calendar is enabled.

Refs https://github.com/owncloud/calendar/issues/604

### CODE REVIEW

**Comment by jbtbnl** [comment]
cc @MorrisJobke @raghunayyar @georgehrke

**Comment by georgehrke** [comment]
Code looks good, will test asap, thx a lot!

**Comment by BernhardPosselt** [comment]
:+1: lets get this merged ;D

**Comment by georgehrke** [comment]
:+1:

**Pull request merged**
