### PR TITLE
force minimum height for event so that 15 minute events are visible

### LINKED ISSUE #256: Feature request : improve visbility of events in day view and week view
If succeeding events occur for example every 15 mins, they cannot be identified at a glance in day view or week view. In month view, the cell height can grow.

A similar behaviour in the two other views would enhance global usability of the calendar.

Thanks for considering.

### PR DESCRIPTION
**Pull request by jancborchardt**
This fixes #256, please test @nmset @aproposnix @georgehrke

### CODE REVIEW

**Comment by ghost** [comment]
Just pulled core, 3rdparty and calendar from git, can't see any resolution of the problem in day view and week view.

**Comment by jancborchardt** [comment]
@nmset to apply this pull request, you first need to switch the branch. In a terminal do this in the calendar repo:
`git checkout -b minimum-event-height origin/minimum-event-height`

Then you can test. To go back to master do `git checkout master`

**Comment by ghost** [comment]
Le mercredi 18 f�vrier 2015 15:43:43 Jan-Christoph Borchardt a �crit :

>  you first need to switch the branch

I have these errors with the advised commands :

fatal: Cannot update paths and switch to branch 'minimum-event-height' at the 
same time.
Did you intend to checkout 'origin/minimum-event-height' which can not be 
resolved as commit?

I cloned from git as follows :

mkdir ocgit
cd ocgit
git clone ......core.git
git clone ......3rdparty.git
cd apps
git clone ......calendar.git

I tried the advised commands in core and calendar.

It it gets too complicated and time consuming for this test, and if others are 
happy with the changes, then I think it's not compelling that I perform the 
test.

Thanks and regards.

**Comment by jancborchardt** [comment]
@nmset then just try: git checkout minimum-event-height

**Comment by ghost** [comment]
Le jeudi 19 f�vrier 2015 04:34:56 Jan-Christoph Borchardt a �crit :

> @nmset then just try: git checkout minimum-event-height

In calendar/ , got this reply :

Already on 'minimum-event-height'

No visual changes noticed up to now in the calendar application with 5 - 15 
mins events.

**Comment by jancborchardt** [comment]
@aproposnix @georgehrke @raghunayyar  can you please cross-test?

**Comment by aproposnix** [comment]
@jancborchardt Unfortunately I'm on a business trip at the moment. I'm afraid I will not be able to help test until Sunday earliest.

**Comment by jancborchardt** [comment]
@aproposnix did you get the time to test this? Thanks! :)

**Comment by aproposnix** [comment]
@jancborchardt 

I can confirm that in day and week view I no longer get the unreadable lines. I even see the overlap. 
Well done! :) 
selection_006

Once #693 is fixed, I'll have the perfect system :D

**Comment by jancborchardt** [comment]
@aproposnix thank you for testing! :)

@georgehrke do I need to backport or do something else for this to be included in the regular release?

**Comment by georgehrke** [comment]
Yes, I'll take care. Need to back port some other changes anyway

**Pull request merged**
