### PR TITLE
OC 6.0.0a - Fixed graphic glitch in "edit event" form

### PR DESCRIPTION
**Pull request by tsumi**
Added width to #fromtime and #totime classes in order to avoid a grapic glitch on "edit event" form in calendar (see screenshot for details)

calendar-glitch

### CODE REVIEW

**Comment by georgehrke** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
@tsumi yes, thank you! Meant to fix that as well, thank you for being faster. :) You’re also welcome to dive into the other design issues and see if you can fix anything. :)

**Comment by jancborchardt** [comment]
@tsumi oooh wait actually it doesn’t fully work. Try it in Chrome – there’s up and down buttons inside the field. We need 70px or 80px for them to fit too. Can you change that?

**Comment by tsumi** [comment]
@jancborchardt set to 80px, i havn't chrome installed now, can you do a quick?

**Comment by jancborchardt** [comment]
@tsumi one other thing: In other languages where the »All day« event checkbox text is short, it’s displayed between the times. To fix that, you can add `width: 100%; float: left;` to `#event-allday`.

**Comment by tsumi** [comment]
Right ... with some "short" language like Japanese this happen ...
Only `width:100%` is needed, with `float:left` same problem happen with Advanced option button :D
owncloud

**Comment by jancborchardt** [comment]
Nice, thank you @tsumi!

**Pull request merged**
