### PR TITLE
Fixes renaming and recoloring of newly created calendar

### PR DESCRIPTION
**Pull request by jbtbnl**
Fix for #484 

Please review @JohnDoe42 @georgehrke

### CODE REVIEW

**Comment by georgehrke** [comment]
works for me :+1:

**Comment by georgehrke** [comment]
can we get another reviewer here? 
maybe @MorrisJobke :)

**Comment by jbtbnl** [comment]
Testing this is really simple, just follow the steps as in https://github.com/owncloud/calendar/issues/484#issue-37510370 :)

**Comment by vgezer** [comment]
This is working for me even without this PR?

**Comment by raghunayyar** [comment]
Got some time here. :+1:

**Pull request merged**
