### PR TITLE
Calendar shared with owner - duplicate calendar fix

### PR DESCRIPTION
**Pull request by ben-denham**
If a user owns a calendar that is also shared with them (e.g. by user1 sharing their calendar with user2, user2 sharing with user3, and user3 sharing with user1 again), the calendar is no longer duplicated in the list returned by OC_Calendar_Calendar::allCalendars() for the user.

### CODE REVIEW

**Comment by jancborchardt** [comment]
@georgehrke can you review this?

**Comment by jancborchardt** [comment]
Also, @michaelzoidl if you want to dive into calendar development then reviewing pull requests like this one might be a good start! :)

**Comment by jancborchardt** [comment]
@nezzi @rysiekpl can you review this please? :)

**Comment by rysiekpl** [comment]
this makes sense, +1 on merging.

**Comment by jancborchardt** [comment]
@rysiekpl did you also test this? (If not, can you do that please? :)

**Comment by schmunk42** [comment]
Please also test the following situation, I stumbled upon it today:
- share a calendar with a group (limited permissions, eg. no delete)
- share the calendar with a person from the above group with full permissions

Permissions are OK (full permissions for the person) so far, but the calendar appears twice in the calendar list of the user.

**Comment by jancborchardt** [comment]
@schmunk42 if you encounter that issue, can you please test if it also happens with this pull request?

**Comment by schmunk42** [comment]
@jancborchardt is there a guide, how to migrate data between two systems (Database, Settings, etc..)?
I have it running in a production system with a vagrant VM, but without git :( But I'll try to find a way.

**Comment by jancborchardt** [comment]
@schmunk42 best set up a dedicated environment for testing. See http://doc.owncloud.org/server/6.0/developer_manual/devenv/index.html#devenv for how to set up a development environment.

**Comment by tanghus** [comment]
> If a user owns a calendar that is also shared with them (e.g. by user1 sharing their calendar with user2, user2 sharing with user3, and user3 sharing with user1 again), 

This scenario I can't get to work, because I get an error message "Sharing 2 failed, because the user user1 is the original sharer"

> share a calendar with a group (limited permissions, eg. no delete)
> share the calendar with a person from the above group with full permissions

This is possible and the PR fixes the issue.

:+1:

**Pull request merged**
