### PR TITLE
some minor design issues

### PR DESCRIPTION
**Pull request by vgezer**
- Fix the layout of the colors
- Wrap long text for clear cache button

Before:

image

After:

image

And...

The "clean cache" button:

Before:

image

After:

image

cc @owncloud/designers

### CODE REVIEW

**Comment by georgehrke** [comment]
@owncloud/designers could you help reviewing here please :)

**Comment by jbtbnl** [comment]
@wakeup unfortunately, it doesn't work for me on Ubuntu, FF:
untitled

**Comment by jbtbnl** [comment]
@wakeup what browser, platform and zoom level are you testing against?

I don't have this issue on master branch with zoom level 100%, but on lower zoom levels the color selectors get misaligned...

**Comment by enoch85** [comment]
Works for me. :+1:

**Comment by vgezer** [comment]
@jbtbnl Hmm. I am using Ubuntu with Chrome 35.. The zoom level is 90%...

What about the clear cache button?

**Comment by jbtbnl** [comment]
@wakeup the cache botton was OK

**Comment by vgezer** [comment]
@jbtbnl Then let's only merge the cache button. The second issue, i will have a look.

**Comment by jbtbnl** [comment]
@wakeup does `.calendar-colorpicker {
    display: inline-block;
}` fix it for you? It does so in Firefox with zoom level 90%.

**Comment by vgezer** [comment]
@jbtbnl Yes! Now, both problems are fixed. I committed it as well.

**Comment by raghunayyar** [comment]
nice, looks good for me on Chrome. Havent tested FF on Mac yet. :+1:

**Comment by vgezer** [comment]
New commit for editing calendar dialog.

The buttons have margin. Before, they were overridden by some other property.

Please test again.

**Comment by vgezer** [comment]
@owncloud/designers Can you review this please?

**Comment by jbtbnl** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@georgehrke 3 :+1:'s should be enough to merge ;)

**Pull request merged**
