### PR TITLE
remove possibility to overwrite on import

### PR DESCRIPTION
**Pull request by jancborchardt**
Every time I want to import an event, I get scared at the import form. This checkbox to potentially delete the whole calendar is just a bit too easy to click.

If you really want to overwrite the calendar, then you should delete it in the calendar app. No need for the dangerous »yeah sure destroy my data while doing other stuff« checkbox.

@georgehrke @jbtbnl please review. :) (There’s some other »overwrite« stuff in the code which is just at »0«, not sure if it should also be ripped out.)

### CODE REVIEW

**Comment by jbtbnl** [comment]
It could also be hidden like "Advanced options" as seen when creating an appointment.

I'm not sure what the use-case for the function would be but sometimes it is easier to just empty your calendar if you are not interested in past appointments instead of deleting duplicates afterwards.

**Comment by jancborchardt** [comment]
It’s a dialog with a single use – importing an event. We don’t need »advanced options« for a second option that probably no one is ever going to use.

**Comment by jancborchardt** [comment]
I mean – importing an event to the Calendar through uploading the ICS to Files and then opening it is completely undiscoverable anyway …

**Comment by jbtbnl** [comment]
You are right, the ICS upload function should be located in the Calendar app. Opening an ICS file through Files is just a nice gimmick.

**Comment by knallio** [comment]
Before you remove that feature, I just want to add that I actually use this. The only way to use my work calendar at the moment is to upload the whole calendar (automatically) from outlook at work via webdav to owncloud. Then I open that calendar file in Files and replace the old one, using the delete checkbox. 
One suggestion: I could live with an "are you sure" popup. This way, deleting the calendar by accident should be impossible, and I have only one click more.

**Comment by jancborchardt** [comment]
@knallio adding yet another popup will not solve things, but just add frustrations. People generally do not read popups but just click »ok«.

But interesting you mention that you need to use this workaround … why is it not possible to use CalDAV? Also, ownCloud is a calendar server, not really a client – so you would just not have the work calendar in the web interface – but instead on your mobile device and desktop.
Is your work calendar subscribable in some way, like via password-protected ICS?

Short: What can we do to fix your problem properly?

**Comment by knallio** [comment]
As far as I can see, outlook does not support caldav. You need to pay for a 3rd-party add-in. So I was kind of happy that it was at least possible to upload the calendar via webdav.

**Comment by knallio** [comment]
To answer your question: I am not sure what you can do to fix my problem, since it is a limitation in outlook. What might help is a way to define an "external" calendar source in the calendar app. which would point to the ics file. That way I can skip the whole import process and everything would be automatic. As far as I understood, this might be possible with the calendar rework?

**Comment by craigarno** [comment]
> As far as I can see, outlook does not support caldav. You need to pay for a 3rd-party add-in.

Would something like this work?  http://sourceforge.net/projects/outlookcaldav/

Addendum: couldn't find anything to download.  i.e. only looks like a framework for the project, nothing deliverable yet.
Wonder if there are other "free" solutions available today?

Like http://support.atmail.com/display/A7DOCS/Outlook+CalDAV+Synchronization+Setup
Download CalDAV support:  http://download.atmail.com/getsync.php

**Comment by knallio** [comment]
@craigarno Yes and no. In principle it would work, but I doubt that I can convince our IT department to install any add-in in that direction, especially an alpha version with (as far as I can see) very little activity. But thanks for the suggestion.

**Comment by georgehrke** [comment]
@knallio Are you the admin of the ownCloud instance and can execute cron jobs on the server? Then you might be interested in https://github.com/georgehrke/cl-calendarimport

**Comment by jbtbnl** [comment]
@georgehrke nice, I didn't know such a script did exist already. Why isn't this part of the calendar app? It shouldn't be too difficult to create some sort of scheduler that runs this periodically.

**Comment by knallio** [comment]
@georgehrke That might be a great solution. I am the admin of the ownCloud instance. However, I cannot execute cron jobs, but I might find a solution. Some kind of integration would be cool, maybe as an additional app, making it configurable from within owncloud. Is there a way to hook into ownclouds cron system (AJAX) in case one cannot use the servers cron? 

I will definitely have a look at that script, thank you!

**Comment by jancborchardt** [comment]
So – can we merge this pull request? The checkbox and possibility to lose my whole calendar creeps me out every single time I import an .ics

**Comment by jbtbnl** [comment]
I believe it can be merged, but I'll leave that up to the calendar maintainers.

@knallio please open an issue for the integration of the import script with the calendar app by means of the owncloud cron system. It is a good idea!

**Comment by georgehrke** [comment]
@jancborchardt Wouldn't simply reverting https://github.com/owncloud/calendar/commit/6ef96d21fc4397cb101567b63e3c9038e9202449 be easier?

**Comment by georgehrke** [comment]
@jancborchardt  I've never used this feature at all, but you can see there are users who actually use this feature. Simply removing a feature that has been there for quite some time isn't really the way we should handle things like this.

**Comment by jancborchardt** [comment]
@georgehrke well, I would say on the other hand »simply adding features which we don’t really know the use of isn’t really the way we should handle things«. ;)

But now I’m not really sure anymore if removing it is better than leaving it there anyway. It’s difficult enough to import an event so let’s maybe leave it.

**Pull request closed without merging**
