### PR TITLE
Use the doctrine code to rename the tables

### PR DESCRIPTION
**Pull request by bartv2**
@georgehrke

### CODE REVIEW

**Comment by jancborchardt** [comment]
:+1: solves #127 for me. Thank you!

**Comment by jancborchardt** [comment]
@georgehrke I hope you tested it as well though …

**Comment by georgehrke** [comment]
yes, I tested it already last weekend.

**Comment by jancborchardt** [comment]
Then thumbing up would be cool to let others know. And it helps to ask for more reviewers. :)

**Pull request merged**
