### PR TITLE
only set DTEND VALUE if DTSTART has VALUE set.

### PR DESCRIPTION
**Pull request by gvde**
Set VALUE parameter of DTEND to the same as DTSTART but only if DTSTART has the parameter set.

### CODE REVIEW

**Comment by georgehrke** [comment]
code looks good, need some testers here.

**Comment by gvde** [comment]
new backport to stable8.2 in #1004
do you need backport to stable8.1, too?

**Comment by cecilebraun** [comment]
A backport for stable 8.1 will be wonderful.

**Comment by gvde** [comment]
Backport to 8.1 in #1022

**Pull request merged**
