### PR TITLE
remove cache setting, do not bother people with options like these

### PR DESCRIPTION
**Pull request by jancborchardt**
If at all, this cache should be automatically cleaned. This should not be a setting.

Please review @georgehrke @owncloud/designers

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: 

Never used that, no idea what it is...

**Comment by georgehrke** [comment]
this is necessary for some users, we should keep it. it's in the settings, so users don't see it all the time

**Comment by jancborchardt** [comment]
Can you explain »necessary for some users«? I have not seen that in any other calendar web app. Could we not have it be done automatically, much like expiring old versions?

**Comment by libasys** [comment]
I am confirm with @georgehrke, this setting clears the repeating Table in the database and fill the repeating calendar events.

**Comment by jancborchardt** [comment]
Yeah, I don’t get why this is a button for users to press. This should be done automatically if anything.

**Comment by georgehrke** [comment]
If we would do this automatically for all users at the same time it would !@#$ the server

**Comment by MorrisJobke** [comment]
@georgehrke ~~Then simulate the trigger of the button on "Save event".~~ Update: Sorry mixed that up. I thought it is in the event view, but it's in the settings view.

**Comment by jancborchardt** [comment]
If doing it automatically for _all_ users at the _same_ time would mess up the server, do it automatically but _not_ for all users at the same time?

**Comment by jancborchardt** [comment]
@georgehrke what about my above comment? Like clearing it automatically when you use the calendar?

**Comment by georgehrke** [comment]
can we please show the button when debug mode is enabled

**Comment by jancborchardt** [comment]
@georgehrke yeah. Just add that in this pull request – I don’t know how to hook that up.

**Comment by georgehrke** [comment]
okay, will add asap

**Comment by georgehrke** [comment]
master: https://github.com/owncloud/calendar/commit/f7e426c09a556e9fa4100740ca0fab81bcc379a0
stable7: https://github.com/owncloud/calendar/commit/eea79827d2b6c350d1ca07dd2093d5143a599b42

**Comment by jancborchardt** [comment]
Thanks!

**Pull request closed without merging**
