### PR TITLE
Fix for firefox time shift in day and week view

### PR DESCRIPTION
**Pull request by adanielvv**
see this issue: https://github.com/owncloud/calendar/issues/616

### CODE REVIEW

**Comment by georgehrke** [comment]
cc @owncloud/designers

**Comment by georgehrke** [comment]
fixes https://github.com/owncloud/calendar/issues/616

**Comment by DeepDiver1975** [comment]
tested :+1:

**Comment by adanielvv** [comment]
Thanks!
This was my first pull request ever after my first comment ever on GitHub.

**Comment by jancborchardt** [comment]
@DanielvV cool, thank you! :) Sorry for the long reaction time, but we hope to see more contributions from you. Especially the Calendar app needs contributors, cc @georgehrke @raghunayyar

**Pull request merged**
