### PR TITLE
Fix share icon for Firefox

### PR DESCRIPTION
**Pull request by jbtbnl**
@codecrusher64 @georgehrke @RealRancor please check out this fix for #661.

I tested it on Chrome and Firefox on Ubuntu, please contribute your findings on other platforms.

### CODE REVIEW

**Comment by codecrusher64** [comment]
I checked it on my platform with Firefox and Chrome. Both show share icon correctly now.

**Comment by Aschen** [comment]
Ok with Firefox 34.0.5 on Windows 7.

Thanks

**Comment by jbtbnl** [comment]
@georgehrke should this be backported?

**Comment by georgehrke** [comment]
yes, I'll take care

**Comment by jancborchardt** [comment]
Wait – icon-shared is a different icon than icon-share! And one we shouldn’t use anymore.

**Comment by jancborchardt** [comment]
We need to fix this in AdBlock and let the Adblock devs know to exclude that.

**Comment by ghost** [comment]
Yes, as core is also affected by this Adblock rule:

https://github.com/owncloud/core/issues/8360#issuecomment-69195136

**Pull request merged**
