### PR TITLE
update SabreDAV to 1.8.10

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by georgehrke** [comment]
is this necessary for ownCloud 7 or shall I merge it afterwords?

**Comment by DeepDiver1975** [comment]
OC7 relevant - dependent on https://github.com/owncloud/core/pull/8724

I'll write a mail to the dev-ml later

**Comment by georgehrke** [comment]
ok, thx

**Comment by ghost** [comment]
You should update to saber/dav 2.0.1 -- lot of new features (incl. read-only calendars).  The PHP 5.4 requirement might be a deal-breaker for you though.

**Comment by DeepDiver1975** [comment]
> The PHP 5.4 requirement might be a deal-breaker for you though.

yes - we cannot move to php 5.4 right now

**Comment by DavidPrevot** [comment]
FWIW, I cherry picked this for the 7.0.0~alpha1 Debian package and it seems to work as intended (disclaimer: I’m not a big user of this app).

**Comment by olenchenko** [comment]
Yesterday I have created an [issue #9011](https://github.com/owncloud/core/issues/9011) regarding similar error in Contacts module. As @requist suggested I have applied #431 and owncloud/contacts#501 - contacts sync works fine now but all calendars are disabled (no dates at all - empty).

**Comment by georgehrke** [comment]
@olenchenko is there any error message?

**Comment by olenchenko** [comment]
No errors, only in debug mode:
`{"reqId":"539b02f51cd97","app":"core","message":"OC\\Tags::loadTags, tags: Array\n(\n    [1] => Birthday\n    [2] => Business\n    [3] => Call\n    [4] => Clients\n    [5] => Deliverer\n    [6] => Holidays\n    [7] => Ideas\n    [8] => Journey\n    [9] => Jubilee\n    [10] => Meeting\n    [11] => Other\n    [12] => Personal\n    [13] => Projects\n    [14] => Questions\n    [15] => Work\n)\n","level":0,"time":"2014-06-13T13:56:05+00:00","method":"GET","url":"\/index.php\/apps\/calendar\/js\/l10n.php"}
{"reqId":"539b02f51cd97","app":"core","message":"OC\\Tags::loadTags, tags: Array\n(\n    [1] => Birthday\n    [2] => Business\n    [3] => Call\n    [4] => Clients\n    [5] => Deliverer\n    [6] => Holidays\n    [7] => Ideas\n    [8] => Journey\n    [9] => Jubilee\n    [10] => Meeting\n    [11] => Other\n    [12] => Personal\n    [13] => Projects\n    [14] => Questions\n    [15] => Work\n)\n","level":0,"time":"2014-06-13T13:56:05+00:00","method":"GET","url":"\/index.php\/apps\/calendar\/js\/l10n.php"}`

**Comment by georgehrke** [comment]
nothing in the server's error log even when you configure php to report everything?

**Comment by olenchenko** [comment]
I have
`error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT`
`display_errors = On`
in my php.ini and apache loglevel set to debug but still nothing in apache logs.

Not sure if it is relevant but settings button does not work on calendar page (works fine on contacts page).

**Comment by requist** [comment]
@georgehrke I have the same problem and did log an error, euhm debug error message, it's noted in #449

**Comment by georgehrke** [comment]
@requist Did you have an error similar to 'Illegal string offset 'uri' at ...' when testing the contacts app?

**Comment by georgehrke** [comment]
I added an commit that should fix the issue.
@requist @olenchenko Do you have spare time to retest this patch?

**Comment by requist** [comment]
@georgehrke Check, this works! :+1:

**Comment by georgehrke** [comment]
thx for testing! let's get this merged :)

**Comment by DeepDiver1975** [comment]
@georgehrke  Awesome!

**Pull request merged**
