### PR TITLE
Don't array_merge the generated event output if the generation failed

### PR DESCRIPTION
**Pull request by ghost**
Fix for #234

### CODE REVIEW

**Comment by georgehrke** [comment]
looks good :+1:

**Comment by georgehrke** [comment]
cc @jancborchardt @kabum

**Comment by MorrisJobke** [comment]
looks good :+1:

**Comment by MorrisJobke** [comment]
@nezzi @georgehrke What about the licensing of this code? Or did you (@nezzi) already signed the contributors agreement? Or how is this handled in apps? 

cc @MTRichards I need a crash course in licensing ;)

**Comment by georgehrke** [comment]
contributors agreement is only necessary if you contribute to core repo

**Comment by ghost** [comment]
I haven't signed a contributors agreement, but please feel free to use/license my patch in any way you'd like; consider it public domain.

**Pull request merged**
