### PR TITLE
Remove OC_Migrate provider

### PR DESCRIPTION
**Pull request by LukasReschke**
See https://github.com/owncloud/core/pull/12380

### CODE REVIEW

**Comment by georgehrke** [comment]
Will this migration system by superseded by another one or do we completely remove migration?

**Comment by georgehrke** [comment]
:+1:

**Comment by LukasReschke** [comment]
> Will this migration system by superseded by another one or do we completely remove migration?

For now it will be just gone, see https://github.com/owncloud/core/issues/12346#issuecomment-63969969 - it didn't worked properly anyways and broke all the things => Let's kill it.

**Comment by georgehrke** [comment]
okay, thx

**Pull request merged**
