### PR TITLE
Make calendar ready for oc 9.0

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@georgehrke @Henni @irgendwie please review and test

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
same for contacts https://github.com/owncloud/contacts/pull/1083

**Comment by georgehrke** [comment]
code itself looks good from my pov, will test tomorrow

**Comment by DeepDiver1975** [comment]
@georgehrke ping - THX

**Comment by georgehrke** [comment]
works :+1:

**Comment by georgehrke** [comment]
@DeepDiver1975 Thx for fixing it :blush:

**Comment by DeepDiver1975** [comment]
My pleasure

**Pull request merged**
