### PR TITLE
Select links when clicked

### PR DESCRIPTION
**Pull request by vgezer**
Users were needed to ~~double~~ triple click to select the whole addresses.

~~This makes the selection automatic like the calendars' CalDAV link.~~

This makes selection only clicking once instead of three.

### CODE REVIEW

**Comment by georgehrke** [comment]
But you actively click to get the caldav link, so automatic selection is the best there.
Primary calendar and principals urls are visible all the time, so mouseover to select could be a bit annoying and unexpected.

@jancborchardt What's your opinion?

**Comment by vgezer** [comment]
Another thing can be clicking once to select the link. This case is more convenient.

**Comment by jancborchardt** [comment]
Yeah, for a link which is displayed all the time, selection should take one click. But not happen on hover - keep in mind it needs to work on tablets too.

**Comment by vgezer** [comment]
@georgehrke @jancborchardt Ok. Now they are selected when clicked only once. 

Can someone test it on tablets?

PS: I checked this on mobile. However, hovering on calendars' CalDAV link on mobile scrolls down the navigation_pane and makes it unable to copy the links. Can we modify it somehow?

**Comment by jancborchardt** [comment]
Yup, works :+1:

@georgehrke @jbtbnl code review please?

**Comment by georgehrke** [comment]
code looks good :+1:

**Comment by georgehrke** [comment]
@wakeup thanks for your contribution :)

**Pull request merged**
