### PR TITLE
Use DI for principal backend

### PR DESCRIPTION
**Pull request by LukasReschke**
Required for https://github.com/owncloud/core/pull/12960

### CODE REVIEW

**Comment by georgehrke** [comment]
looks good, will test asap (or you can merge it if you are 100% sure that it works)

**Comment by LukasReschke** [comment]
@georgehrke If you want to test this together with https://github.com/owncloud/core/pull/12960 and give me :+1: there as well you would be my hero of the week ;-)

**Comment by georgehrke** [comment]
I will try, but I will definitely not find time before 10pm today

**Comment by derkostka** [comment]
:+1:

**Comment by georgehrke** [comment]
:+1:

**Pull request merged**
