### PR TITLE
make search results app specific

### PR DESCRIPTION
**Pull request by butonic**
requires https://github.com/owncloud/core/issues/12555 to be merged, will make this app require oc8

### CODE REVIEW

**Comment by PVince81** [comment]
Please change info.xml as well to make it require OC 8 ?

**Comment by PVince81** [comment]
Other than that :+1:

**Comment by butonic** [comment]
@MorrisJobke

**Comment by georgehrke** [comment]
Code changes look good, will test asap

Please excuse my brevity and typos.

**Comment by MorrisJobke** [comment]
Looks good :+1:

**Comment by MorrisJobke** [comment]
@georgehrke Ping

**Comment by georgehrke** [comment]
:+1:

**Pull request merged**
