### PR TITLE
Prevent selection effect on accidental selection

### PR DESCRIPTION
**Pull request by pldubouilh**
Prevent the light blue color (depends on the os) due to an accidental selection. Same fix as the one for the navbar.

Before :

After : well, no blue color !

### CODE REVIEW

**Comment by georgehrke** [comment]
@owncloud/designers Could you help testing :smile:

**Comment by jbtbnl** [comment]
@pldubouilh how to reproduce the accidental selection?

**Comment by pldubouilh** [comment]
Drag and drop from the left "banner" to the calendar



or more annoying triple click on the calendar itself :



or Ctrl + A ...

**Comment by jbtbnl** [comment]
@pldubouilh OK, I can't reproduce that (except for the Ctrl + A), it is probably browser specific. Guessing from the color, is there anyone of @owncloud/designers running on Windows that can verify and check this? (or Linux + Chromium maybe)

**Comment by pldubouilh** [comment]
The screenshots previously posted were taken on Chromium (Mac OS 10.9 - 37.0.2057.0 (277990)), and on Safari.

Have the same issue with Firefox on Ubuntu 14.01.1

**Comment by georgehrke** [comment]
I can confirm that it fixes this issue in Chromium on OS X - :+1:

**Comment by georgehrke** [comment]
@jbtbnl just start selecting over the sidebar and move onto fullcalendar

**Comment by jbtbnl** [comment]
:+1:

**Pull request merged**
