### PR TITLE
fix js and css loading for owncloud 8

### PR DESCRIPTION
**Pull request by BernhardPosselt**
Moves all scripts and styles to index.php so that they are only loaded when the calendar is actually opened and not when you launch the News app for instance. Also the first paramter to addScript is the application name and this breaks various things in core if you just use a hack like the path

@georgehrke @raghunayyar

### CODE REVIEW

**Comment by georgehrke** [comment]
everything in appinfo/app.php is needed for the ical import in the files app. So moving them to index.php will break the import dialog.

**Comment by PVince81** [comment]
Isn't that a case where addVendorScript() can be used ?
CC @MorrisJobke

**Comment by georgehrke** [comment]
I agree that we should load the chosen and minicolor js/css after the ical file was clicked, so we only load the calendar/js/loader.js file

**Comment by BernhardPosselt** [comment]
@georgehrke separate template? If so it should be added there

**Comment by georgehrke** [comment]
add it where? in the files app? That's not a real solution as all apps (including 3rdparty ones) are supposed to register file handers for the files app

**Comment by BernhardPosselt** [comment]
Ah, files app. Why do we support this again?

**Comment by BernhardPosselt** [comment]
We should a wrapper then like if ($currentApp === 'files')

**Comment by georgehrke** [comment]
> We should a wrapper then like if ($currentApp === 'files')

That would be a good work-around for now. Could you add it to your pr please?

**Comment by BernhardPosselt** [comment]
Done I simply preg_match the url since there is no working api that gets you the currently active app. If the files app was written using the app framework we could match it using the route id

**Comment by georgehrke** [comment]
awesome thanks!, will test asap

**Comment by DeepDiver1975** [comment]
tested works :+1:

**Comment by PVince81** [comment]
:+1: works

**Pull request merged**
