### PR TITLE
Googlefix

### PR DESCRIPTION
**Pull request by ghost**
This automatically fixes the invalid events sometimes generated by Google Calendar.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Can you review this fix @georgehrke @tanghus?

**Comment by jancborchardt** [comment]
@ben-denham @rysiekpl can you test and review this please? :)

**Comment by georgehrke** [comment]
:+1:

**Comment by georgehrke** [comment]
Thanks for your contribution :)

**Pull request merged**
