### PR TITLE
Fix checkboxes

### PR DESCRIPTION
**Pull request by Henni**
Reorder labels of checkboxes to work with the new checkbox styles (#18735).

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Is this the way we want this to looks like?

bildschirmfoto von 2015-10-12 12-36-24

**Comment by Henni** [comment]
@DeepDiver1975 Probably not. I'll take another look.

**Comment by Henni** [comment]
image

now looks like this and should fallback to the normal checkboxes in 8.1 and before.

**Comment by DeepDiver1975** [comment]
THX :+1:

**Pull request merged**
