### PR TITLE
Event sharing fixes

### PR DESCRIPTION
**Pull request by ben-denham**
A couple of fixes related to individually shared events:
- When retrieving a list of events that have been shared with a user: events that belong to calendars that the user can access are ignored. This prevents events from being shown twice on the calendar view.
- A new "Shared events" calendar is displayed in the list of calendars. This calendar allows users to hide/show all events that have been individually shared with them. This solves the problem of someone individually sharing 100 spam events with you, and you having no way to hide them.

### CODE REVIEW

**Comment by jancborchardt** [comment]
@georgehrke can you check this out as well? Also @michaelzoidl take a look at this if you like. :)

**Comment by jancborchardt** [comment]
@nezzi @rysiekpl can you review this? :) If everyone tests everyone elses pull requests, we can fix stuff much faster. :)

**Comment by tanghus** [comment]
Tested and works :+1: 
@georgehrke shall I merge?

**Comment by georgehrke** [comment]
If it works, go ahead and merge it!
Thanks for help with reviewing. I really appreciate it.

**Comment by tanghus** [comment]
np

**Comment by jancborchardt** [comment]
@tanghus you’re awesome! :) Thank you for reviewing the pulls.

**Comment by tanghus** [comment]
:blush:

**Pull request merged**
