### PR TITLE
add file actions only when OCA.Files is available

### PR DESCRIPTION
**Pull request by butonic**
@PVince81 @georgehrke @raghunayyar a quick review pls

### CODE REVIEW

**Comment by PVince81** [comment]
Does this work from the "Shared with XXX" view ?
You might need to fix the open method of the handler to also read the "dir" property from the context. Because flat views like "Shared with XXX" need that extra info.
See here for an example: https://github.com/owncloud/music/blob/master/js/public/musicFilePlayer.js#L57

**Comment by PVince81** [comment]
Note that the old `FileActions` only works for "All files" while the new `OCA.Files.FileActions` is designed to work with all file lists.

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2015-10-12 14-04-20
- [ ] The action appears as 'Edit' without an icon
- [ ] Clicking Edit opens the text editor

**Comment by georgehrke** [comment]
@DeepDiver1975 Is the OCA.Files.fileActions api documented somewhere?

**Comment by PVince81** [comment]
not yet...

there is also another approach: https://github.com/owncloud/activity/blob/master/lib/fileshooksstatic.php#L43 and https://github.com/owncloud/activity/blob/master/lib/fileshooksstatic.php#L98

This would only load the JS files when the file apps is visible.

**Comment by PVince81** [comment]
(only works in 8.2)

**Comment by DeepDiver1975** [comment]
I'm fixing this for 8.2

**Comment by georgehrke** [comment]
Thanks :blush:

**Comment by DeepDiver1975** [comment]
Ah - the Edit is from the text editor ..... will submit PR there

**Comment by DeepDiver1975** [comment]
> Ah - the Edit is from the text editor ..... will submit PR there

@jancborchardt @PVince81 I assume it is intended to have an icon on the action menu

**Comment by DeepDiver1975** [comment]
@PVince81 please review - THX

**Comment by PVince81** [comment]
Looks good :+1:

**Pull request merged**
