### PR TITLE
Fix non ascii character display on calendar share dialog

### PR DESCRIPTION
**Pull request by vgezer**
Before, sanitizeHTML for displaying the name of the calendar was being
encoded. This was causing non-ascii characters to be shown strange.
This should fix this problem. Since this is only a display text,
sanitizing should not be a problem.

### CODE REVIEW

**Comment by vgezer** [comment]
ping

**Comment by georgehrke** [comment]
@LukasReschke p() already sanitizes the output, so this should be XSS safe, right?

**Comment by LukasReschke** [comment]
@georgehrke Yup

**Comment by georgehrke** [comment]
Thanks for your contribution :)

**Pull request merged**
