### PR TITLE
Design fixes as mentioned in #467

### PR DESCRIPTION
**Pull request by enoch85**
@jancborchardt Lets make a new try. :smile: 

This is some of the changes as discussed here https://github.com/owncloud/calendar/issues/467

Here it should be Torsdag 26 Jun. 2014 as I have changed it to in my code. 
Second should be Torsdag 26/6 (didn´t find that)

namnls1

Here it should be 30 Jun. 2014 - 6 Jul. 2014 as I have changed to in my code.
("MMM d[ yyyy]{ '–'[ MMM] d yyyy}" => "d[ MMM yyyy]{ '–'[ d] MMM yyyy}",)
Second should be Mån. 30 Jun. (dindn´t find that) Looks cleaner

namnls2

### CODE REVIEW

**Comment by georgehrke** [comment]
@jancborchardt when reviewing please do need merge, this needs to be fixed on transifex :)

@enoch85 thx for the pull request

**Comment by enoch85** [comment]
@georgehrke I have already made the changes on transifex (Swedish, not the original) so maybe the best thing would be to wait for the changes to take effect before we start discussing here?

**Comment by jancborchardt** [comment]
cc @owncloud/designers

**Comment by enoch85** [comment]
It seems like the changes was made already to the Swedish calendar.po, but not sv.php: https://github.com/owncloud/calendar/commit/73cc53b33ea922b2e13606b7d71ec33a30960eb8

Does it take like 3 days for the changes made on Transifex to take effect in the daily build?
Day one: Translaton is made on Transifex
Day two:. ownCloud-bot syncs the translation with ownCloud git
Day three: The changes are included in the daily build.

**Comment by jancborchardt** [comment]
@DeepDiver1975 can you answer @enoch85’s translation question?

**Comment by vgezer** [comment]
@enoch85 You do not need to do Pull Requests until we freeze translation sync. Just change them in Transifex and wait until the next sync :).

As an answer to your question, all new strings are pushed and the updated translations are pulled at the same time.

According to the Jenkin's log, the translations have been pulled around 08:00. You can see the latest pulled sv.php [here](https://github.com/owncloud/calendar/blob/73cc53b33ea922b2e13606b7d71ec33a30960eb8/l10n/sv.php).

And it seems, the daily builds are built before translation sync. That's why you should wait one more day to test them. You are right.

**Comment by enoch85** [comment]
@wakeup Thank you for the info!

In other words, this pull is kind of unnecessary as all the changes can be made directly on Transifex. That´s good to know! :)

The question still remains if the changes should be made to the original string as well? 

Anyway, I will close this Pull for now and wait for the changes to take effect in the next daily build.

**Comment by vgezer** [comment]
@enoch85 Do you mean the original English strings? If there is a typo you can use [this](https://github.com/owncloud/core/issues/8904) issue to report such things.

**Comment by enoch85** [comment]
FYI, All the fixes in this PR came with this daily build trough Transifex.

**Pull request closed without merging**
