### PR TITLE
shorten calendar db names

### PR DESCRIPTION
**Pull request by georgehrke**

### CODE REVIEW

**Comment by butonic** [comment]
sorry, this just causes other garbage in out SQL table definitions to bubble up:

``` sql
CREATE  TABLE "oc_clndr_objects" ("id" NUMBER(10) DEFAULT 0 NOT NULL, "calendarid" NUMBER(10), "objecttype" VARCHAR2(40), "startdate" DATE DEFAULT '0000-00-00 00:00:00', "enddate" DATE DEFAULT '0000-00-00 00:00:00', "repeating" NUMBER(10), "summary" VARCHAR2(255), "calendardata" CLOB, "uri" VARCHAR2(255), "lastmodified" NUMBER(10))
                                                                                                                                                   *
ERROR at line 1:
ORA-01847: day of month must be between 1 and last day of month
```

`0000-00-00 00:00:00` is interpreted as `NULL` by most other DBs not so with oracle. it should be possible to leave out the default value for the timestamp column.

an explanation: http://stackoverflow.com/questions/11133759/0000-00-00-000000-can-not-be-represented-as-java-sql-timestamp-error

**Comment by georgehrke** [comment]
ping @butonic

**Comment by butonic** [comment]
Awesome! The testsuite now completes! There are some errors, but they are unrelated to the calendar app. Please merge this quickly.

@DeepDiver1975 we are getting there ...

```
Configuration read from /home/jfd/Repositories/oc/core/tests/phpunit-autotest.xml

........................................IIISS..SSEEEEEEF.FF...F  63 / 499 ( 12%)
.F.FF..FFFFFFFF................................................ 126 / 499 ( 25%)
..F.....F..F..............................IIIII...............I 189 / 499 ( 37%)
IIII.............I....FE......................E..E............. 252 / 499 ( 50%)
..................................................EE........E.. 315 / 499 ( 63%)
.E...........................IE................................ 378 / 499 ( 75%)
............................................................... 441 / 499 ( 88%)
...........I..............F...................FSSFFFEFF..F

Time: 01:50, Memory: 47.75Mb
```

**Comment by butonic** [comment]
yeah! sweet!

**Comment by georgehrke** [comment]
@butonic @karlitschek Do I need to backport this to stable5 ?

**Comment by karlitschek** [comment]
Yes please

**Pull request merged**
