### PR TITLE
Add 4-Weeks view

### PR DESCRIPTION
**Pull request by citronalco**
Shows the current week at the top, followed by the next 3 weeks, like in Google Calendar

### CODE REVIEW

**Comment by georgehrke** [comment]
cc @jancborchardt

**Comment by georgehrke** [comment]
4 weeks view should replace month review, no need to have both

**Comment by citronalco** [comment]
disagreed. month view and 4 weeks view are used for different purposes. removing month view would irritate many users. including myself.

**Comment by georgehrke** [comment]
there is no real benefit of month view, if there is a 4 week view

**Comment by jancborchardt** [comment]
Totally agree with @georgehrke. The month view is useless if there is a proper 4 week view which puts the current week up top.

For reference see this post by Marco Arment: http://www.marco.org/2010/03/28/more-ideas-than-time-logarithmic-calendar-view

**Comment by jancborchardt** [comment]
Even better of course would be if the whole thing would be continuous …: #360 ;)

cc @jbtbnl on this as well – what do you think?

**Comment by citronalco** [comment]
I totally agree with Marco Arment when it's about the current month or the next month.
But I really prefer having the first day of the month on top when planning events far in the future, e.g. my christmas vacation next year.

**Comment by jbtbnl** [comment]
@jancborchardt honestly I did not know that Google calendar has a 4-week view :smile: I use my calendar mainly in week view because of the amout of detail I've got in it. To make a new appointment in the future I  navigate to the right week via the datepicker.

Anyway, I am not against the fact that others want a 4-week view or whatever additional view. I might even end up using it! Just keep in mind that it will clutter the UI more.

**Comment by jbtbnl** [comment]
@citronalco would you please rebase this so that we can test it with the new sidebar?

**Comment by jancborchardt** [comment]
@citronalco can you rebase this? :) If you need help, just ask here.

**Comment by citronalco** [comment]
See https://github.com/owncloud/calendar/pull/511
And yes, I really should improve my git knowledge.

**Pull request closed without merging**
