### PR TITLE
Possible Fix #463

### PR DESCRIPTION
**Pull request by libasys**
Possible Fix for https://github.com/owncloud/calendar/issues/463
Please use the label only for the checkbox and not for the whole line, it runs into problems with the sharing dialog box!

### CODE REVIEW

**Comment by georgehrke** [comment]
cc @owncloud/designers 

@libasys thx

**Comment by vgezer** [comment]
Unfortunately, it does not solve the issue, but I think this is :+1:

**Comment by MorrisJobke** [comment]
As @wakeup said: I doesn't fix the issue, but semantically its a better representation :+1:

**Comment by georgehrke** [comment]
:+1:

**Comment by georgehrke** [comment]
@libasys thx for the patch :)

**Comment by georgehrke** [comment]
stable7: https://github.com/owncloud/calendar/commit/49e8185

**Pull request merged**
