### PR TITLE
Style fixes

### PR DESCRIPTION
**Pull request by jancborchardt**
Fixing the button size, and also removing the padding to make Fullcalendar use the whole content area.

Why are the controls all in form elements by the way? That leads to unnecessary DOM elements.

cc @georgehrke

### CODE REVIEW

**Comment by jancborchardt** [comment]
Can someone review this and pull it in? @georgehrke @owncloud/designers

**Comment by Niduroki** [comment]
:+1:

**Comment by jancborchardt** [comment]
Great, thanks! Now please also check out the other 4 Calendar pull requests: https://github.com/owncloud/calendar/pulls

**Comment by georgehrke** [comment]
I've no time right now. would be great if others could help to review these pull requests

**Comment by raghunayyar** [comment]
@georgehrke @jancborchardt will do that in a day. :)

**Pull request merged**
