### PR TITLE
Possible fix for #530

### PR DESCRIPTION
**Pull request by basc**

### CODE REVIEW

**Comment by georgehrke** [comment]
please review @brantje

**Comment by basc** [comment]
Possible fix for #530

**Comment by georgehrke** [comment]
code changes look good :+1:, didn't test

**Comment by brantje** [comment]
Code looks good :+1:

**Comment by jancborchardt** [comment]
@georgehrke @brantje so can you then actually test, so we can merge it? :)

**Comment by georgehrke** [comment]
haven't tested yet, won't find time for testing before weekend. you are welcome to help testing :smile:

**Comment by basc** [comment]
I've tested it and the error in #530 is gone with this fix.

**Comment by jancborchardt** [comment]
@SunboX @carstengumz can you test if this fixes https://github.com/owncloud/calendar/issues/530 for you?

**Comment by rodrigoaguilera** [comment]
I tested the PR and it works for me

**Comment by jancborchardt** [comment]
@georgehrke please handle the backporting.

**Comment by georgehrke** [comment]
Wait, why was this pull request made against stable7 :disappointed:

**Pull request merged**
