### PR TITLE
Fix URL encoding for iOS/OS X CalDAV address

### PR DESCRIPTION
**Pull request by ghost**
Proposal for problem described in https://github.com/owncloud/calendar/issues/937

### CODE REVIEW

**Comment by gvde** [comment]
This is probably better than my initial #938.

**Comment by ghost** [comment]
Copied over from: https://github.com/owncloud/calendar/pull/938#issuecomment-143981507

> @RealRancor I didn't see that. Using the same way is probably better even if I don't quite understand it. I wonder why quotes (and only quotes) should be entity encoded in the user name. I hope someone thought about it when this was done or otherwise it would need to be revisited...

**Comment by DeepDiver1975** [comment]
@LukasReschke encoding-fu - THX

**Comment by DeepDiver1975** [comment]
tested with cadaver :+1:

**Pull request merged**
