### PR TITLE
Implement getChild() - fixes #832

### LINKED ISSUE #832: [oC 8.1] can no longer sync shared calendars
I just updated my server to the 8.1 branch, both master and calendar. The update went well but my mobile phone can no longer sync a calender which was shared with me, the calendar is shared with all permissions. I have this errror in the owncloud.log:

````
{"reqId":"uhWpnxn9mptSHnMcjLXG","remoteAddr":"95.115.156.48","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 403 User did not have the required privileges ({DAV:}read) for path \\\"calendars\\\/schiesbn\\\/sandra_shared_by_sandra\\\/20150707T070517Z-28296_607c92ea4cae4279.ics\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(769): Sabre\\\\DAVACL\\\\Plugin->checkPrivileges('calendars\\\/schie...', '{DAV:}read')\\n#1 [internal function]: Sabre\\\\DAVACL\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/appsSelected\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php\",\"Line\":223}","level":4,"time":"2015-07-07T12:10:06+00:00"}
````

Any idea what's wrong?

cc @georgehrke 
cc @PVince81 afaik you also worked on the sabredav update for 8.1

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@georgehrke @schiesbn

### CODE REVIEW

**Comment by georgehrke** [comment]
fixes the issue for me :+1: 
thx a lot

**Comment by DeepDiver1975** [comment]
never walk again without unit tests - we could have caught this weeks back

**Comment by DeepDiver1975** [comment]
> never walk again without unit tests - we could have caught this weeks back

seriously - all this angular-fu is pointless if the server breaks apart

**Comment by schiessle** [comment]
Awesome! Tested and works! :+1: :beer:

**Comment by jancborchardt** [comment]
@georgehrke is this fix pushed to the App store?

**Comment by georgehrke** [comment]
Yes, it is. v0.7.1

**Comment by jancborchardt** [comment]
:+1: nice!

**Pull request merged**
