### PR TITLE
Remove SanitizeHTML which encodes non-ascii characters while editing cal.

### PR DESCRIPTION
**Pull request by vgezer**
- Create a calendar with a non-ascii character: eg. üçöğ
- Edit the calendar with edit link
- The characters are encoded and not possible to see them properly.

@georgehrke What do you think?

### CODE REVIEW

**Comment by vgezer** [comment]
@georgehrke Do we need to backport this also to OC6 and OC5?

**Comment by georgehrke** [comment]
:-1: This will introduce XSS vulnerability.

**Comment by vgezer** [comment]
Then how can we fix this problem?

**Comment by georgehrke** [comment]
closing this in favor of https://github.com/owncloud/core/pull/8168

**Comment by georgehrke** [comment]
double sanitization fixed in https://github.com/owncloud/calendar/commit/742048350a968676b8dae4d05186dd45442f5148

**Pull request closed without merging**
