### PR TITLE
Added (email) reminder support for calendar application

### PR DESCRIPTION
**Pull request by sureshprakash**

### CODE REVIEW

**Comment by jbtbnl** [comment]
@sureshprakash I guess it should be "reminder" (without the a). And could you please move the email body into a template file?

Thanks for contributing :)

**Comment by sureshprakash** [comment]
@jbtbnl Thank you for correcting me. :) New pull request is made at https://github.com/owncloud/calendar/pull/374 after making the corrections you specified. :)

**Comment by georgehrke** [comment]
edit: renamed to Added (email) reminder support for calendar application

**Comment by georgehrke** [comment]
closing this in favor of #374

**Pull request closed without merging**
