### PR TITLE
Fixes Issue #435

### PR DESCRIPTION
**Pull request by acrylschaf**
Fixes issues with yearly reoccurring events on Windows Phone 8 (and possibly other systems). https://github.com/owncloud/calendar/issues/435

### CODE REVIEW

**Comment by georgehrke** [comment]
- [x] please use tabs instead of spaces (1 tab = 4 spaces)

**Comment by acrylschaf** [comment]
Done. Please excuse the inconvenience!

**Comment by georgehrke** [comment]
Thanks :)
Will test asap

**Comment by georgehrke** [comment]
thanks for your contribution :)

**Pull request merged**
